#### Step - 9
- series type
- no column name display
- whenever you see this type: series type

In [4]:
import pandas as pd

In [6]:
list_1 = [i for i in range (1,11)]
list_2 = [i*i for i in range (1,11)]
list_3 = [i*i*i for i in range (1,11)]
print (list_1,'\n', list_2,'\n', list_3)
numbers_df = pd.DataFrame(zip(list_1,list_2,list_3),columns=["Numbers","Square of numbers","Cube of numbers"])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
 [1, 4, 9, 16, 25, 36, 49, 64, 81, 100] 
 [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [8]:
numbers_df

Numbers  Square of numbers  Cube of numbers
0        1                  1                1
1        2                  4                8
2        3                  9               27
3        4                 16               64
4        5                 25              125
5        6                 36              216
6        7                 49              343
7        8                 64              512
8        9                 81              729
9       10                100             1000

In [14]:
numbers_df['Numbers']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Numbers, dtype: int64

In [16]:
numbers_df[['Numbers']]

Numbers
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9
9       10

In [22]:
numbers_df.Numbers

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Numbers, dtype: int64

- numbers_df['Numbers']: series type 
- numbers_df[['Numbers']]: DataFrame type 
- numbers_df.Numebrs: series type

In [25]:
numbers_df["Numbers"].values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

- all values comes in an array 
- it a list of elements only represents using numpy package
- Generally elements present in 3 ways 
    - List: Basic representation
    - Numpy array: Array with Numpy package
    - Tensor: Tensorflow package 
    - Torch: Python package

In [28]:
list1 = [1,2,3,4]
list1

[1, 2, 3, 4]

In [32]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4])

In [34]:
list2 = [10,20,30,40]

In [36]:
list1+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [38]:
np.array([list1,list2])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [40]:
l1= np.array(list1)
l2= np.array(list2)
l1 + l2

array([11, 22, 33, 44])

In [42]:
numbers_df["Numbers"].values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [44]:
numbers_df["NUMB"] = numbers_df['Numbers'].values 
numbers_df

Numbers  Square of numbers  Cube of numbers  NUMB
0        1                  1                1     1
1        2                  4                8     2
2        3                  9               27     3
3        4                 16               64     4
4        5                 25              125     5
5        6                 36              216     6
6        7                 49              343     7
7        8                 64              512     8
8        9                 81              729     9
9       10                100             1000    10

#### Step-10 
**How to save a DataFrame**
- Dataframes we can save in two formats
    - csv: comma seperated value
    - xlsx: excel format
- in order to save nay data
    - Where you want to save: Directory name
    - what is the name of the file for storing
    - what is the extension
- we already know about the file Handling session

$Case-1$
- saving file at same location
- so directory path is not required
- directly give only the name of the file and the extention 

In [54]:
# DataFrame name 
numbers_df.to_csv('numbers1.csv')
numbers_df.to_excel('number1.xlsx')

In [56]:
import os 
os.getcwd()

'C:\\Users\\mohit\\Data_Science\\In_Class\\EDA'

In [58]:
import pandas as pd 
pd.read_excel('number1.xlsx')

Unnamed: 0  Numbers  Square of numbers  Cube of numbers  NUMB
0           0        1                  1                1     1
1           1        2                  4                8     2
2           2        3                  9               27     3
3           3        4                 16               64     4
4           4        5                 25              125     5
5           5        6                 36              216     6
6           6        7                 49              343     7
7           7        8                 64              512     8
8           8        9                 81              729     9
9           9       10                100             1000    10

#### Step-11
**How to avoid the unnamed column**
- while we save the dataframe
- automatically a new column will be created
- that we need to avoid
- permission denied means that we need to close the file that is open that we are trying to edit
- index=False will remove the unnamed column while saving
- we can update the files by doing the below by using the same name as file again

In [65]:
numbers_df.to_csv('numbers1.csv',index=False)
numbers_df.to_excel('number1.xlsx',index=False)